Repository bookwyrm-social/bookwyrm, pull requests merged in 2025-09, with the labels that each got.

#3692 Improve Unicode support in slugs and URL patterns
  bookwyrm/models/base_model.py
  bookwyrm/tests/models/test_unicode_slugs.py
  bookwyrm/utils/regex.py
Labels: enhancement

#3694 Add DublinCore metadata to Book page
  bookwyrm/templates/book/book.html
  bookwyrm/templates/snippets/dublincore.html
Labels: enhancement, data

#3670 Allow S3 Default ACL Override for Backblaze
  .env.example
  bookwyrm/settings.py
Labels: fix, config-change

#3699 Allow S3 Default ACL Override
  .env.example
  bookwyrm/settings.py
Labels: config-change
